srcdir=src
builddir=build
classdir=class
ant.home=C:\Users\samjadhav\Downloads\apache-ant-1.10.15-bin\apache-ant-1.10.15
artifactory.url=http://localhost:8081/artifactory/student-libs-local
artifactory.user=admin
artifactory.password=password
jar.name=StudentManager.jar
